name: Main Branch Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm ci
    - name: Run backend tests
      working-directory: ./backend
      run: |
        npm test -- --verbose

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        npm test


    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: maepatante/CD_automatisation
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
