name: Feature to Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm ci
        npm run build --if-present
        npm test
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm ci
        npm run build --if-present
        npm test
    
    - name: Trigger dev-to-main merge workflow
      if: success() 
      run: |
        echo "Triggering dev-to-main workflow"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
